# Generated by Django 4.2.4 on 2023-09-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0003_alter_usermodel_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(
                blank=True, max_length=30, null=True, unique=True, verbose_name="Почта",
            ),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="is_verify_email",
            field=models.BooleanField(default=False),
        ),
    ]
