# Generated by Django 4.2.4 on 2023-08-22 23:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_rename_userprofile_userblog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBlog',
            new_name='UserProfile',
        ),
    ]
