# Generated by Django 4.2.4 on 2023-08-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_postmodel_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentmodel",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="static/",
                verbose_name="Фотография",
            ),
        ),
    ]
